# Generated by Django 3.0.6 on 2020-06-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
