# Generated by Django 3.0.7 on 2020-06-27 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
